# Generated by Django 4.2.16 on 2024-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailsending', '0002_alter_emailsession_template_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsession',
            old_name='is_scheduled',
            new_name='one_off',
        ),
    ]
